---
title: "Mapa LISA - Departamento de Lima"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
# Links de los mapas (.rds)

map1link="https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Evaluaci-n-final/raw/main/map1.rds"
viz1=url(map1link)

map2link="https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Evaluaci-n-final/raw/main/map2.rds"
viz2=url(map2link)

map3link="https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Evaluaci-n-final/raw/main/map3.rds"
viz3=url(map3link)

map4link="https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Evaluaci-n-final/raw/main/map4.rds"
viz4=url(map4link)
```

## Sidebar {.sidebar}

### Análisis LISA

Este dashboard compara los resultados del análisis LISA para los distritos del departamento de Lima utilizando cuatro criterios de vecindad:

- Queen
- Rook
- K-nearest neighbors (KNN)
- Perimeter

## Column {.tabset .tabset-fade}

### Queen

```{r}
readRDS(viz1)
```

### Rook

```{r}
readRDS(viz2)
```

### KNN

```{r}
readRDS(viz3)
```

### Perimeter

```{r}
readRDS(viz4)
```

